train:
  _target_: src.datasets.CustomDirDataset
  limit: 1
  part: "train"
  dataset_name: "test-clean"
  roi_kwargs:
    top_left: [65, 118]
    height: 256
    width: 256
  codec_name: "codec_16x16_128"
  lensless_tag: "measured" # lensless dir name is f"lensless_{lensless_tag}"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.CustomDirDataset
  limit: 1
  part: "test-clean"
  dataset_name: "example"
  roi_kwargs:
    top_left: [65, 118]
    height: 256
    width: 256
  codec_name: "codec_16x16_128"
  lensless_tag: "measured"
  instance_transforms: ${transforms.instance_transforms.inference}
