test_aes_128:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement"
  instance_transforms: ${transforms.instance_transforms.inference}
  sim_psf_config: ${psf}
  randomize_psf_percent: 96 # 4% correct
  randomize_psf_seed: 55
test_aes_256:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement"
  instance_transforms: ${transforms.instance_transforms.inference}
  sim_psf_config: ${psf}
  randomize_psf_percent: 93 # 7% correct
  randomize_psf_seed: 56
