train:
  _target_: src.datasets.LibrispeechDataset
  max_audio_length: 3
  part: "train-clean-100"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement" # lensless dir name is f"lensless_{lensless_tag}"
  instance_transforms: ${transforms.instance_transforms.train}
  sim_psf_config: ${psf}
test:
  _target_: src.datasets.LibrispeechDataset
  limit: 1
  max_audio_length: 3
  part: "test-clean"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement"
  instance_transforms: ${transforms.instance_transforms.inference}
  sim_psf_config: ${psf}
music_test:
  _target_: src.datasets.SongDescriberDataset
  limit: 1
  part: "test"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement"
  instance_transforms: ${transforms.instance_transforms.inference}
  sim_psf_config: ${psf}
