test:
  _target_: src.datasets.SongDescriberDataset
  part: "test"
  roi_kwargs: ${reconstruction.roi_kwargs}
  codec_name: ${codec.codec_name}
  lensless_tag: "measurement"
  instance_transforms: ${transforms.instance_transforms.inference}
  sim_psf_config: ${psf}
