device: "auto"
train:
  - _target_: src.metrics.SISDRMetric
    name: "SISDR"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISDRMetric
    name: "SISDR"
  - _target_: src.metrics.STOIMetric
    name: "STOI"
  - _target_: src.metrics.WERMetric
    name: "WER"
  - _target_: src.metrics.PSNRMetric
    name: "PSNR"
  - _target_: src.metrics.GMSDMetric
    name: "GMSD"
  - _target_: src.metrics.MSEMetric
    name: "MSE"
