_target_: src.model.LenslessWrapper
use_loader: false
loader_kwargs: null
use_batch_video_version: false
freeze_weights: false

# define psf for initialization
psf_path: data/digicam_psf/SIM_psf.png
psf_loader_kwargs:
  downsample: 8
  return_bg: false
grayscale_psf: true

# define lensless model
recon_name: ADMM
recon_kwargs:
  # Number of iterations
  n_iter: 10
