_target_: src.model.LenslessWrapper
use_loader: false
loader_kwargs: null
use_batch_video_version: false
freeze_weights: True

# define psf for initialization
psf_path: data/digicam_psf/SIM_psf.png
psf_loader_kwargs:
  downsample: 8
  return_bg: false
grayscale_psf: true

# define lensless model
recon_name: UnrolledADMM
recon_kwargs:
  # Number of iterations
  n_iter: 10
  # Hyperparameters
  mu1: 1e-4
  mu2: 1e-4
  mu3: 1e-4
  tau: 2e-4
