_target_: src.model.LenslessWrapper
use_loader: false
loader_kwargs: null
use_batch_video_version: false
freeze_weights: false

# define psf for initialization
psf_path: data/capture/digicam_psf_june16/SIM_psf.png
psf_loader_kwargs:
  downsample: 8
  return_bg: false

# define lensless model
recon_name: UnrolledADMM
recon_kwargs:
  # Number of iterations
  n_iter: 5
  # Hyperparameters
  mu1: 1e-4
  mu2: 1e-4
  mu3: 1e-4
  tau: 2e-4
  pre_process:
    _target_: lensless.recon.drunet.network_unet.UNetRes
    in_nc: 2 # grayscale +
    out_nc: 1 # grayscale
    nc: [32, 64, 112, 128]
    nb: 4
    act_mode: "R"
    downsample_mode: "strideconv"
    upsample_mode: "convtranspose"
  post_process:
    _target_: lensless.recon.drunet.network_unet.UNetRes
    in_nc: 2 # grayscale +
    out_nc: 1 # grayscale
    nc: [32, 64, 116, 128]
    nb: 4
    act_mode: "R"
    downsample_mode: "strideconv"
    upsample_mode: "convtranspose"
  psf_network:
    _target_: lensless.recon.drunet.network_unet.UNetRes
    in_nc: 2 # grayscale +
    out_nc: 1 # grayscale
    nc: [4,8,16,32]
    nb: 4
    act_mode: "R"
    downsample_mode: "strideconv"
    upsample_mode: "convtranspose"
  psf_residual: false
  skip_unrolled: false
  return_intermediate: false
