_target_: src.model.LenslessWrapper
use_loader: false
loader_kwargs: null
use_batch_video_version: false
freeze_weights: false

# define psf for initialization
psf_path: data/digicam_psf/SIM_psf.png
psf_loader_kwargs:
  downsample: 8
  return_bg: false
grayscale_psf: true

# define lensless model
recon_name: UnrolledADMM
recon_kwargs:
  post_process:
    _target_: lensless.recon.drunet.network_unet.UNetRes
    in_nc: 2 # grayscale +
    out_nc: 1 # grayscale
    nc: [32, 64, 128, 256]
    nb: 4
    act_mode: "R"
    downsample_mode: "strideconv"
    upsample_mode: "convtranspose"
  psf_residual: false
  skip_unrolled: True # makes sure that only the post_process is used, no PSF
  return_intermediate: false
