slm: adafruit
sensor: rpi_hq
downsample: 8

# https://drive.switch.ch/index.php/s/NdgHlcDeHVDH5ww?path=%2Fpsf
# pattern: data/capture/digicam_psf_june16/adafruit_random_pattern_20250616_151951.npy
# ap_center: [55, 77]
# ap_shape: [18, 24]
rotate: -0.8   # rotation in degrees
vertical_shift: -20 # [px]
horizontal_shift: -20  # [px]


# whether SLM is flipped
flipud: True

# in practice found waveprop=True or False doesn't make difference
use_waveprop: True
deadspace: True

# below are ignored if waveprop=False
scene2mask: 0.3   # [m]
mask2sensor: 0.004   # [m]

# grayscale
grayscale: True
