_target_: src.transforms.CodecEncoderDecoder
codec_cls: ${resolve_class:dac.DAC}
codec_weights_path: data/dac_exps/${codec.codec_name}/latest/dac/weights.pth
codec_add_root_path: True
codec_kwargs: null
codec_name: "16x16_130_16khz"
eval_mode: True
freeze_weights: True
