train:
  all: # use dict as input
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.PadCrop
        length: 4
        pad_format: "replicated"
        random_crop: true
        frames_per_lensless: 1
inference:
  all:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.PadCrop
        length: 16
        pad_format: "replicated"
        random_crop: false
        frames_per_lensless: 1
